### ISSUE TITLE
Audio Distortion

### ISSUE THREAD

**Issue by forrestpark** [maxzinkus/AtypicalSpeech#1]
Audio recordings made with distortions - [sample recordings with distortions](https://livejohnshopkins-my.sharepoint.com/:f:/r/personal/lmorove1_jh_edu/Documents/Atypical_Speech_Project/Audios/TestForJangWoo?csf=1&web=1&e=m0hHIg](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Flivejohnshopkins-my.sharepoint.com%2F%3Af%3A%2Fr%2Fpersonal%2Flmorove1_jh_edu%2FDocuments%2FAtypical_Speech_Project%2FAudios%2FTestForJangWoo%3Fcsf%3D1%26web%3D1%26e%3Dm0hHIg&data=05%7C01%7Cjpark278%40jhu.edu%7C31ebb88473f24e6762d308db548cea44%7C9fa4f438b1e6473b803f86f8aedf0dec%7C0%7C0%7C638196736423236176%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D4lp928cSNscRK7VX53Qr9SK8QkLvZHjJMCgAW7s0lM%3D&reserved=0))

The issue seems to be happening for a couple of other users of the 'audio-react-recorder' library. [Link to issue](https://github.com/doppelgunner/audio-react-recorder/issues/13)

Depends on the device, but on the device currently deployed at the hospital, distortion starts to happen around the 7th or 8th consecutive recording with the distortion worsening afterwards.

I have tried modifying audio settings of audio-react-recorder ([ex](https://stackoverflow.com/questions/49477768/poor-audio-quality-with-getusermedia-any-ideas-why)) and have attempted changing audio formats but have not been able to produce any meaningful improvement in audio quality.

'audio-react-recorder' does seem to be an abandoned library; have also explored other libraries as a last resort ([ex](https://www.npmjs.com/package/react-audio-voice-recorder)). Please let me know if you have any recommendations on switching to another recording library, or potentially build one ourselves (expensive, though).

**Comment by ameriania** [comment]
Have you ever tried these two audio recorders as an alternative solution? You mentioned one of the below, maybe we can have a quick switch to a new library to test.
1. react-audio-voice-recorder: https://github.com/samhirtarif/react-audio-recorder
2. react-audio-analyser:https://github.com/jiwenjiang/react-audio-analyser

**Comment by ameriania** [comment]
# Audio Distortion Follow Up

[Distorted Voice Samples](https://livejohnshopkins-my.sharepoint.com/personal/lmorove1_jh_edu/_layouts/15/onedrive.aspx?csf=1&web=1&e=m0hHIg&cid=03081870%2D3430%2D4796%2D971b%2D9074d9695214&id=%2Fpersonal%2Flmorove1%5Fjh%5Fedu%2FDocuments%2FAtypical%5FSpeech%5FProject%2FAudios%2FTestForJangWoo&FolderCTID=0x01200088D8B421F6FC5542A21684A6D8B68C6C&view=0)

## Issue Address

Based on the related code I have reviewd, it seemds like there is none of our business when using the current provided libarary named audio-react-recorder, which leads to the distorted recording. One of alternative solutions is to use another library to rebuild the same feature, and it also help us way more easier to maintain the code in the later future. However,  what we need to know is we can not guarantee it would not lead to distortion again, due to they are using very similar technique among each other.

## Solutions

| Library                                                      | Demo                                                         | Core                         | Support      | Last    |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ---------------------------- | ------------ | ------- |
| [audio-react-recorder](https://github.com/doppelgunner/audio-react-recorder) | [Demo1](https://doppelgunner.github.io/audio-react-recorder/) | React = 16 + getUserMedia    | wav          | 3 years |
| [react-audio-recorder](https://github.com/samhirtarif/react-audio-recorder) | [Demo2](https://stackblitz.com/edit/react-ts-cc5l47?file=App.tsx) | React>=16.2.0 + mediaDevices | wav/mp3/webm | 5 days  |
| [react-audio-analyser](https://github.com/jiwenjiang/react-audio-analyser) | [Demo3](https://jiwenjiang.github.io/)                       | React = 16.4 + getUserMedia  | wav/mp3/webm | 1 year  |

## Browser Support

A really important information we need to know, no matter based on which technique we use, our recoding feature doesn't support IE browser. And we need to figure out what browsers are used in the hospital's scenario.
<img width="674" alt="image" src="https://github.com/maxzinkus/AtypicalSpeech/assets/17880183/baf5543f-9bb6-4a1f-846e-522482ad5d2b">
<img width="673" alt="image" src="https://github.com/maxzinkus/AtypicalSpeech/assets/17880183/1965321b-d3de-4746-bea7-1f8a9e9fd215">
